# Generated by Django 2.1.1 on 2018-10-04 14:32

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(max_length=200, unique=True)),
                ('object_order', models.PositiveIntegerField(default=0)),
                ('company_name', models.CharField(max_length=200)),
                ('company_URL', models.URLField()),
                ('start_date', models.CharField(max_length=200)),
                ('finish_date', models.CharField(max_length=200)),
                ('description', ckeditor.fields.RichTextField()),
            ],
            options={
                'verbose_name': 'Job',
                'verbose_name_plural': 'Jobs',
                'ordering': ['object_order'],
            },
        ),
    ]
