import type { Metadata } from "next";

import MouseFollow from "./components/MouseFollow";
import Navigation from "./components/Navigation";

import "@/app/styles/global.scss";

export const metadata: Metadata = {
  title: "Testing app",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="app">
        <MouseFollow />
        <Navigation />
        {children}
      </body>
    </html>
  );
}
